/**
 * Local filesystem storage for uploaded PDF/EPUB files, keyed by an opaque
 * storageKey stored on Article.fileStorageKey. Swapping this for S3 later
 * means replacing this module's three functions, not any of their callers.
 */
import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const STORAGE_ROOT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "storage",
);

function keyToPath(storageKey: string): string {
  // storageKey is always generated by saveFile below (userId/uuid.ext) --
  // never derived from user input -- so this can't be used for traversal.
  return path.join(STORAGE_ROOT, storageKey);
}

export async function saveFile(userId: string, originalFilename: string, data: Buffer): Promise<string> {
  const ext = path.extname(originalFilename).toLowerCase() || "";
  const storageKey = `${userId}/${randomUUID()}${ext}`;
  const filePath = keyToPath(storageKey);

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, data);

  return storageKey;
}

export async function readStoredFile(storageKey: string): Promise<Buffer> {
  return readFile(keyToPath(storageKey));
}

export async function deleteStoredFile(storageKey: string): Promise<void> {
  await rm(keyToPath(storageKey), { force: true });
}
