/**
 * Local filesystem storage for uploaded PDF/EPUB files, keyed by an opaque
 * storageKey stored on Article.fileStorageKey. Swapping this for S3 later
 * means replacing this module's three functions, not any of their callers.
 */
import { randomUUID } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { ReadStream } from "node:fs";

const STORAGE_ROOT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "storage",
);

function keyToPath(storageKey: string): string {
  // storageKey is always generated by saveFile below (userId/uuid.ext) --
  // never derived from user input -- so this can't be used for traversal.
  return path.join(STORAGE_ROOT, storageKey);
}

export async function saveFile(userId: string, originalFilename: string, data: Buffer): Promise<string> {
  const ext = path.extname(originalFilename).toLowerCase() || "";
  const storageKey = `${userId}/${randomUUID()}${ext}`;
  const filePath = keyToPath(storageKey);

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, data);

  return storageKey;
}

/** A live read stream, not a fully-buffered read -- for a large upload (a
 * scanned book can easily be tens of MB), reading the whole thing into one
 * Buffer first holds the *entire* file in memory before the route sends a
 * single byte back, meaning the client's download can't even start until
 * disk I/O for the whole file finishes server-side. Streaming instead lets
 * bytes start reaching the client (and, for a PDF being opened via pdf.js,
 * start being parsed) as soon as they're off disk, not after. */
export function streamStoredFile(storageKey: string): ReadStream {
  return createReadStream(keyToPath(storageKey));
}

export async function deleteStoredFile(storageKey: string): Promise<void> {
  await rm(keyToPath(storageKey), { force: true });
}
